server:
  port: 8080
spring:
  #数据库连接配置
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/2026-test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath*:com/example/esdemo/mapper/sqlMap/*.xml
  type-aliases-package: com.example.esdemo
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true